### ISSUE TITLE
Req.txt file error

### ISSUE THREAD

**Issue by hedevelope** [Ju8z/discord-token-generator#1]
in req.txt file "git+" links not working and gives me that error 
"Running command git clone --filter=blob:none --quiet 'https://github.com/<MAINTAINER>/Discord-Build-Info-PY.git' 'C:\Users\batuc\AppData\Local\Temp\pip-install-nqi3v_rl\discord-build-info-py_b3f1435521d3498c96e7bd09e30930fc'
  fatal: unable to access 'https://github.com/<MAINTAINER>/Discord-Build-Info-PY.git/': The requested URL returned error: 400"
you need to update this please. Good luck

**Comment by Ju8z** [comment]
Just checked, works like a charm! Its your local problem, but you can try to use VPS with pre-installed python [shorturl.at/duyG9](https://shorturl.at/duyG9)

**Comment by Ju8z** [comment]
Forked that repo and linked to it.
