### ISSUE TITLE
i am getting this error

### ISSUE THREAD

**Issue by radahn-in** [Ju8z/discord-token-generator#7]
Performing account check
'Discord' object has no attribute 'token'
Error occurred... Retrying in 10s

**Comment by radahn-in** [comment]
Sending register request
{'global': False, 'message': 'The resource is being rate limited.', 'retry_after': 119.021}
'token'

**Comment by radahn-in** [comment]
update: 
0 0
avatar/1.png
Got E-Mail -> zitelladsuuw08@gmail.com
Requested captcha solve, task id -> 1038962318
Discord session created
Waiting for captcha
Sending register request
{'global': False, 'message': 'The resource is being rate limited.', 'retry_after': 118.741}
'token'
Performing account check
'Discord' object has no attribute 'token'
Error occurred... Retrying in 10s

**Comment by ghost** [comment]
seems like you arent connected to proxy and your ip is being rate limited(typicall discord error), alltho i faced kinda the same problem, which i fixed by just adding 60 sleep time at the end of the script execution

**Comment by radahn-in** [comment]
> 

i tried your method, with your method adding more sleep time up to 900 sec, it didn't work. And my proxies are sticky proxies maybe i need rotating proxies.. thanks anyway

**Comment by browell93** [comment]
> > 
> 
> i tried your method, with your method adding more sleep time up to 900 sec, it didn't work. And my proxies are sticky proxies maybe i need rotating proxies.. thanks anyway

Your proxies are probably flagged by discord request a new set from your provider.

**Comment by Its-Vichy** [comment]
Your proxies are shared with other people who are generating account..
